title: <center>Dreamline91's TIL</center>
description: <hr>TIL is abbreviation for Today I Learned.<br>I upload what I study in Software.
show_downloads: true
theme: jekyll-theme-minimal

#Collections
collections:
 MCNL:
  output: true
  permalink: /:collection/:path/

#etc
profile: https://avatars1.githubusercontent.com/u/7951335?v=4
home: http://dreamline91.xyz
