title: <center>Dreamline91's TIL</center>
description: <hr>TIL is abbreviation for Today I Learned.<br>I upload what I study during graudate school.
show_downloads: true
author: dreamline91
theme: jekyll-theme-minimal

#Collections
collections:
 TIL:
  output: true
  permalink: /:collection/:path/

#etc
avatar: https://avatars1.githubusercontent.com/u/7951335?v=4
favicon: assets/personal/img/bird.png
image: http://dreamline91.xyz/static/personal/img/profile.jpg
home: http://dreamline91.xyz
profile: profile
name: Jae Jun Ha
email: dreamline91@postech.ac.kr
interest: Graphics/Network
hobby: Programming/Art/Marathon
bucketlist: Freelance <b>Programmer</b> or IT <b>specialist</b><br><b>Artist</b> who can draw what I want to express<br>Sub-3 <b>Marthoner</b><br>through <b>Meditation</b>, be calm<br>learn many <b>Foreign Language</b>s
education: <b>MS</b> Postech(ing...)<br><b>BS</b> Ajou University, software (rank 1/82)

